name: Github variables

on:
  push:
    branches:
      - main
jobs:
  pr-number:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: get_pr_data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
            console.log(${{ fromJson(steps.get_pr_data.outputs.result).head }})

      - name: Pull Request data
        run: |
          echo '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
          echo '${{ fromJson(steps.get_pr_data.outputs.result).title }}'
          echo '${{ fromJson(steps.get_pr_data.outputs.result).user.login }}'
          echo '${{ fromJson(steps.get_pr_data.outputs.result).html_url }}'
          echo '${{ fromJson(steps.get_pr_data.outputs.result).head.ref }}'
          
          JIRA_TICKET=$(echo ${{ fromJson(steps.get_pr_data.outputs.result).title }} | grep -oE "(^[A-Z]+-[0-9]+(,{1}[A-Z]+-[0-9]+)*|(\(|\[)[A-Z]+-[0-9]+(,{1}[A-Z]+-[0-9]+)*(\)|\])$)" | tr -d '()[]' | head -n1 || true)
          if [ -z "$JIRA_TICKET" ]; then
            echo "No JIRA ticket found in the PR title. Setting default value AST-000"
            JIRA_TICKET="AST-000"
          fi
          echo $JIRA_TICKET