name: Github variables

on:
  push:
    branches:
      - master

jobs:
  PullRequestVariables:
    runs-on: ubuntu-latest
    steps:
      - name: Print pull request info
        run: |
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Commiter Name: ${{ github.event.pull_request.user.login }}"
          echo "Component Name: ${{ github.event.repository.name }}"
          echo "Branch Name: ${{ github.event.pull_request.base.ref }}"
          echo "Commit SHA: ${{ github.sha }}"