name: Github variables

on:
  push:
    branches:
      - main

jobs:
  PullRequestVariables:
    runs-on: ubuntu-latest
    steps:
      ## - name: Print pull request info
      ##   run: |
      ##     echo "Title: ${{ github.event.pull_request.title }}"
      ##     echo "Commiter Name: ${{ github.event.pull_request.user.login }}"
      ##     echo "Component Name: ${{ github.event.repository.name }}"
      ##     echo "Branch Name: ${{ github.ref#refs/heads/ }}"
      ##     echo "Commit SHA: ${{ github.sha }}"
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Pull Request Info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the branch name
          BRANCH_NAME="${{ github.ref }}"
          
          # Query GitHub API to find the PR associated with the branch
          PR_RESPONSE=$(curl -s \
            -H "Authorization: token ${{env.GITHUB_TOKEN}}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:$BRANCH_NAME")
          
          # Extract the first PR in the list (assuming only one open PR for this branch)
          PR_TITLE=$(echo "$PR_RESPONSE" | jq -r '.[0].title')
          COMMITTER_NAME=$(echo "$PR_RESPONSE" | jq -r '.[0].user.login')
          BRANCH_NAME=$(echo "$PR_RESPONSE" | jq -r '.[0].head.ref')
          
          echo "Pull Request Title: $PR_TITLE"
          echo "Committer Name: $COMMITTER_NAME"
          echo "Branch Name: $BRANCH_NAME"