name: Github variables

on:
  push:
    branches:
      - main

jobs:
  PullRequestVariables:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Get Pull Request Info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="${{ github.ref}}"
        
        # Get the pull request details using the branch name
        PR_DATA=$(gh pr list --head "$BRANCH_NAME" --json title,author,headRefName --jq '.[]')
        
        # Extract title, committer (author), and branch name
        PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
        COMMITTER_NAME=$(echo "$PR_DATA" | jq -r '.author.login')
        BRANCH_NAME=$(echo "$PR_DATA" | jq -r '.headRefName')
        
        echo "Pull Request Title: $PR_TITLE"
        echo "Committer Name: $COMMITTER_NAME"
        echo "Branch Name: $BRANCH_NAME"
        
        # You can now use these variables as needed